### ISSUE TITLE
Cannot install with pip

### ISSUE THREAD

**Issue by americanhanko** [Microsoft/InQRy#1]
```
$ pip3 install inqry
Collecting inqry
  Using cached inqry-1.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7w/yzqmnn5128gf_ww4zg7mz07w0000gp/T/pip-build-uz17_p7k/inqry/setup.py", line 23, in <module>
        plist = Plist.fromFile('Info.plist')
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/plistlib.py", line 140, in fromFile
        with _maybe_open(pathOrFile, 'rb') as fp:
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/plistlib.py", line 120, in _maybe_open
        with open(pathOrFile, mode) as fp:
    FileNotFoundError: [Errno 2] No such file or directory: 'Info.plist'
```

**Comment by americanhanko** [comment]
Resolved with 4f0633b6f4b9c12471231d986d562af576eb2ac9
